In [1]:
arr = np.array(1,2,3)
arr

NameError: name 'np' is not defined

In [2]:
arr = [1,2,3,4]
arr

[1, 2, 3, 4]

In [3]:
my_arr = np.array(arr)

NameError: name 'np' is not defined

In [4]:
pip install numpy



     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB ? eta -:--:--
     -------------------------------------- 61.2/61.2 kB 809.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 435.7 kB/s eta 0:00:37
   ---------------------------------------- 0.0/15.8 MB 435.7 kB/s eta 0:00:37
   ---------------------------------------- 0.0/15.8 MB 435.7 kB/s eta 0:00:37
   ---------------------------------------- 0.0/15.8 MB 196.9 kB/s eta 0:01:21
   ---------------------------------------- 0.1/15.8 MB 504.4 kB/s eta 0:00:32
   ---------------------------------------- 0.1/15.8 MB 504.4 kB/s eta 0:00:32
   ---------------------------------------- 0.1/15.8 MB 426.7 kB/s eta 0:00:37
   ---------------------------------------- 0.2/15.8 MB 535.8 kB/s eta 0:00:30
    --------------------------------------- 0.3/15.8 MB 656.4 kB/s eta 0

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'



In [5]:
import numpy as np

In [6]:
my_arr = np.array(arr)

In [7]:
my_arr

array([1, 2, 3, 4])

In [8]:
my_arr.dtype()

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [9]:
my_arr.dtype

dtype('int32')

In [10]:
random_int_array = np.random.randint(1, 50, size=(10))


In [11]:
random_int_array

array([48, 18, 40, 49, 41,  3, 15, 10, 12, 27])

In [12]:
random_int_array.size

10

In [13]:
random_int_array.dtype

dtype('int32')

In [14]:
np.ndim(random_int_array)

1

In [15]:
two_dims_array = np..random.randint(10,100, size =(2,5))

SyntaxError: invalid syntax (1592317061.py, line 1)

In [16]:
two_dims_array = np.random.randint(10,100, size =(2,5))

In [17]:
two_dims_array

array([[53, 84, 23, 33, 55],
       [56, 22, 95, 75, 13]])

In [18]:
two_dims_array.shape

(2, 5)