In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 330.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 546.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 653.6 kB/s eta 0:00:25
   ---------------------------------------- 0.1/15.8 MB 469.7 kB/s eta 0:00:34
   ---------------------------------------- 0.1/15.8 MB 853.3 kB/s eta 0:00:19
   ---------------------------------------- 0.2/15.8 MB 807.1 kB/s eta 0:00:20
    --------------------------------------- 0.2/15.8 MB 734.2 kB/s eta 0:00:22
    --------------------------------------- 0.2/15.8 MB 722.1 kB/s eta 0:00:22
    ----

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
random_int_array = np.random.randint(1, 50, size=10)


In [4]:
random_int_array

array([43, 34,  7, 42, 18, 22, 44, 34, 32, 28])

In [5]:
np.mean(random_int_array)

30.4

In [6]:
three_1 =  np.random.randint(1, 100, size=(3,3))

In [7]:
three_2 = np.random.randint(1, 100, size=(3,3))

In [8]:
three = np.add(three_1,three_2)

In [9]:
three_1

array([[47, 50, 26],
       [37, 68, 99],
       [34, 55, 34]])

In [10]:
three_2

array([[48, 94, 94],
       [78, 75, 84],
       [44, 94, 96]])

In [11]:
three

array([[ 95, 144, 120],
       [115, 143, 183],
       [ 78, 149, 130]])

In [12]:
np.mean(three)

128.55555555555554

In [13]:
twenty =  np.random.randint(1, 100, size=20)

In [14]:
cond = twenty > 50
bigger_50 = twenty[cond]

In [15]:
bigger_50

array([86, 52, 80, 54, 74, 53, 52, 62, 62, 70, 99, 55])

In [16]:
ten =  np.random.randint(1, 100, size=20)

In [23]:
np.random.shuffle(ten)

In [24]:
ten

array([11, 12, 85,  2, 95, 65, 23, 61, 57,  2, 84, 23, 79, 93, 86, 12, 14,
       75,  6, 48])

In [26]:
ten[np.random.randint(1,10)]

85

In [27]:
ten[np.random.randint(1,10)]

2